version: "3"

services:
    db:
        image: postgres:14.0-alpine
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data

    app:
        image: chaunceywe/chaoying.dev
        restart: always
        ports:
            - 80:8000
        env_file:
            - .env
        environment:
            ENVIRONMENT: production
        depends_on:
            - db

volumes:
    postgres-data:
