version: "3"

services:
    db:
        image: postgres:14.0-alpine
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data

    app:
        build: .
        restart: always
        ports:
            - 8000:8000
        env_file:
            - .env
        environment:
            ENVIRONMENT: production
        depends_on:
            - db

    nginx:
        image: nginx:1.21.3-alpine
        ports:
            - 80:80
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    postgres-data:
