version: "3"

services:
    db:
        image: postgres:14.0-alpine
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data

    app:
        image: chaunceywe/chaoying.dev
        restart: always
        env_file:
            - .env
        environment:
            ENVIRONMENT: production
        depends_on:
            - db
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.fastapi.rule=Host(`chaoying.dev`)"

    traefik:
        image: traefik:v2.2
        ports:
            - 80:80
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "$PWD/traefik.toml:/etc/traefik/traefik.toml"

volumes:
    postgres-data:
