# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list

  format:
    desc: Format the code (and imports).
    cmds:
      - poetry run isort ./
      - poetry run black ./

  lint:
    desc: Run the linting checks.
    cmds:
      - pre-commit run --all-files

  dev:
    desc: Start dev server
    cmds:
      - poetry run uvicorn app.main:app  --reload --debug

  test:
    desc: Run the tests.
    cmds:
      - poetry run pytest -rs -p no:warnings

  coverage:
    desc: Get the test coverage (xml and html) with the current version.
    cmds:
      - poetry run coverage run -m pytest -rs -p no:warnings
      - poetry run coverage report -m
      - poetry run coverage xml
      - 'echo "Generated XML report: ./coverage.xml"'
      - poetry run coverage html
      - 'echo "Generated HTML report: ./htmlcov/index.html"'

  setup:
    desc: Configure the development environment.
    cmds:
      - task: setup:pre-commit-hook
      - task: setup:poetry-setup

  setup:pre-commit-hook:
    cmds:
      - pre-commit install
    status:
      - test -f .git/hooks/pre-commit

  setup:poetry-setup:
    cmds:
      - poetry install
    sources:
      - pyproject.toml
